[versions]
kotlinTarget = "2.1"
javaTarget = "17"

kotlin = "2.1.0"
kotlinxSerialization = "1.7.3"
kotest = "6.0.0.M1"

bignum = "0.3.10"

versionsPlugin = "0.51.0"
dokkaPlugin = "2.0.0-Beta"
publishPlugin = "2.0.0"

binaryCompatibilityValidatorPlugin = "0.16.3"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-json = { module = "io.kotest:kotest-assertions-json", version.ref = "kotest" }
bignum = { module = "com.ionspin.kotlin:bignum", version.ref = "bignum" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-plugin-power-assert = { id = "org.jetbrains.kotlin.plugin.power-assert", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokkaPlugin" }
dokka-javadoc = { id = "org.jetbrains.dokka-javadoc", version.ref = "dokkaPlugin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versionsPlugin" }
publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "publishPlugin" }
kotlinx-binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref ="binaryCompatibilityValidatorPlugin" }
